Bump tsc-watch from 6.0.4 to 6.2.0 (#46)
Bumps [tsc-watch](https://github.com/gilamran/tsc-watch) from 6.0.4 to
6.2.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/gilamran/tsc-watch/releases">tsc-watch's
releases</a>.</em></p>
<blockquote>
<h2>feature: Using prepublish</h2>
<p>No release notes provided.</p>
<p>feature: --noEmit. thanks to <a
href="https://github.com/llllvvuu"><code>@​llllvvuu</code></a></p>
<p>fix: error TS6369: Option '--build' must be the first command line
argument. thanks to <a
href="https://github.com/llllvvuu"><code>@​llllvvuu</code></a> for the
PR</p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/gilamran/tsc-watch/blob/master/CHANGELOG.md">tsc-watch's
changelog</a>.</em></p>
<blockquote>
<h2>v6.2.0 - 28/03/2024</h2>
<ul>
<li>feature: Using prepublish. thanks to <a
href="https://github.com/llllvvuu"><code>@​llllvvuu</code></a></li>
</ul>
<h2>v6.1.0 - 27/03/2024</h2>
<ul>
<li>feature: --noEmit. thanks to <a
href="https://github.com/llllvvuu"><code>@​llllvvuu</code></a></li>
</ul>
<h2>v6.0.5 - 27/03/2024</h2>
<ul>
<li>fix: error TS6369: Option '--build' must be the first command line
argument. thanks to <a
href="https://github.com/llllvvuu"><code>@​llllvvuu</code></a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/gilamran/tsc-watch/commit/321fde98400a46444469afa051ef7189f10e7c9a"><code>321fde9</code></a>
6.2.0</li>
<li><a
href="https://github.com/gilamran/tsc-watch/commit/0b82c957ade1e30522e35e71dce59cae336423f6"><code>0b82c95</code></a>
Add prepublish feature</li>
<li><a
href="https://github.com/gilamran/tsc-watch/commit/34f90235bf83803bf7ad1b6ed715211d095618d4"><code>34f9023</code></a>
Merge pull request <a
href="https://redirect.github.com/gilamran/tsc-watch/issues/168">#168</a>
from llllvvuu/fix/prepublishOnly</li>
<li><a
href="https://github.com/gilamran/tsc-watch/commit/56b0f30ccf2dccd8a85c0da91c9ac8d34ab639a6"><code>56b0f30</code></a>
build: run build in prepublishOnly</li>
<li><a
href="https://github.com/gilamran/tsc-watch/commit/3f879777db65c35ccd459283b0ba1db25cb05ecc"><code>3f87977</code></a>
6.1.0</li>
<li><a
href="https://github.com/gilamran/tsc-watch/commit/e3c9e203bbcd405c4a67a4ba3a8f23c2982c6a47"><code>e3c9e20</code></a>
Add --noEmit feature, thanks to <a
href="https://github.com/llllvvuu"><code>@​llllvvuu</code></a></li>
<li><a
href="https://github.com/gilamran/tsc-watch/commit/673fcaf9f5eff7973ee6cbf4c5001c57740f78f4"><code>673fcaf</code></a>
Merge pull request <a
href="https://redirect.github.com/gilamran/tsc-watch/issues/167">#167</a>
from llllvvuu/feat/on_emit</li>
<li><a
href="https://github.com/gilamran/tsc-watch/commit/1c266ae26fb1dd2e1206f93cb0899909bb63262d"><code>1c266ae</code></a>
fix ascii art</li>
<li><a
href="https://github.com/gilamran/tsc-watch/commit/37cd23be9aff87f74471e1cc407ff9495f26f7d5"><code>37cd23b</code></a>
Update README.md</li>
<li><a
href="https://github.com/gilamran/tsc-watch/commit/13653cc40c60203511e09c9dc0159e7a066237e5"><code>13653cc</code></a>
Update README.md</li>
<li>Additional commits viewable in <a
href="https://github.com/gilamran/tsc-watch/compare/v6.0.4...v6.2.0">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=tsc-watch&package-manager=npm_and_yarn&previous-version=6.0.4&new-version=6.2.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>